## 1.3.1 Задание
    Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
    единицами.


In [17]:
import numpy as np
a = np.arange(0, 64).reshape(8, 8)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            a[i][j] = 0
        else:
            a[i][j] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
!pip install numpy


  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/b7/98/5640a09daa3abf0caeaefa6e7bf0d10c0aa28a77c84e507d6a716e0e23df/numpy-2.1.1-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-2.1.1-cp312-cp312-win_amd64.whl.metadata (59 kB)
Using cached numpy-2.1.1-cp312-cp312-win_amd64.whl (12.6 MB)



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## 1.3.2 Задание
    Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
    необходимо использовать функцию arrange.

In [10]:
import numpy as np
a = np.arange(0, 25).reshape(5, 5)
for i in range(5):
    for j in range(5):
        a[i][j] = a[i][j] - 5 * i
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 1.3.3 Задание
    Создать массив 3x3x3 со случайными значениями

In [27]:
from random import randint
a = np.arange(27).reshape(3,3,3)
for i in range(3):
    for j in range(3):
        for k in range(3):
            a[i][j][k] = randint(1,100)
print(a, '\n')
n = np.random.random((3,3,3))
print(n)

[[[24 60 52]
  [73 94 74]
  [52 81 18]]

 [[28 55 12]
  [57 18 66]
  [86 11 96]]

 [[12 79 23]
  [59 90 40]
  [29 26 89]]] 

[[[0.43468584 0.66132738 0.90237974]
  [0.33401697 0.91998994 0.182852  ]
  [0.42209141 0.60073994 0.63861161]]

 [[0.70939585 0.62451649 0.58861274]
  [0.7989583  0.47818011 0.31570981]
  [0.79629245 0.93350722 0.17247197]]

 [[0.87611067 0.4371556  0.2869506 ]
  [0.29871719 0.61209111 0.08921704]
  [0.16242997 0.53730674 0.8883887 ]]]


## 1.3.4 Задание
    Создать матрицу с 0 внутри, и 1 на границах

In [31]:
a = np.arange(25).reshape(5, 5)
for i in range(5):
    for j in range(5):
        if i == 0 or i == 4 or j == 0 or j == 0:
            a[i][j] = 1
        else:
            a[i][j] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 1 1 1]]


## 1.3.5 Задание
    Создайте массив и отсортируйте его по убыванию

In [36]:
a = np.array([1, 2 , 4, 5, 6, 3])
print(np.sort(a, key=reversed))

TypeError: sort() got an unexpected keyword argument 'key'