## 1.3.1 Задание
    Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
    единицами.


In [2]:
import numpy as np
a = np.arange(0, 64).reshape(8, 8)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            a[i][j] = 0
        else:
            a[i][j] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
!pip install numpy


  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/b7/98/5640a09daa3abf0caeaefa6e7bf0d10c0aa28a77c84e507d6a716e0e23df/numpy-2.1.1-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-2.1.1-cp312-cp312-win_amd64.whl.metadata (59 kB)
Using cached numpy-2.1.1-cp312-cp312-win_amd64.whl (12.6 MB)



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## 1.3.2 Задание
    Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
    необходимо использовать функцию arrange.

In [10]:
import numpy as np
a = np.arange(0, 25).reshape(5, 5)
for i in range(5):
    for j in range(5):
        a[i][j] = a[i][j] - 5 * i
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 1.3.3 Задание
    Создать массив 3x3x3 со случайными значениями

In [27]:
from random import randint
a = np.arange(27).reshape(3,3,3)
for i in range(3):
    for j in range(3):
        for k in range(3):
            a[i][j][k] = randint(1,100)
print(a, '\n')
n = np.random.random((3,3,3))
print(n)

[[[24 60 52]
  [73 94 74]
  [52 81 18]]

 [[28 55 12]
  [57 18 66]
  [86 11 96]]

 [[12 79 23]
  [59 90 40]
  [29 26 89]]] 

[[[0.43468584 0.66132738 0.90237974]
  [0.33401697 0.91998994 0.182852  ]
  [0.42209141 0.60073994 0.63861161]]

 [[0.70939585 0.62451649 0.58861274]
  [0.7989583  0.47818011 0.31570981]
  [0.79629245 0.93350722 0.17247197]]

 [[0.87611067 0.4371556  0.2869506 ]
  [0.29871719 0.61209111 0.08921704]
  [0.16242997 0.53730674 0.8883887 ]]]


## 1.3.4 Задание
    Создать матрицу с 0 внутри, и 1 на границах

In [31]:
a = np.arange(25).reshape(5, 5)
for i in range(5):
    for j in range(5):
        if i == 0 or i == 4 or j == 0 or j == 0:
            a[i][j] = 1
        else:
            a[i][j] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 1 1 1]]


## 1.3.5 Задание
    Создайте массив и отсортируйте его по убыванию

In [4]:
a = np.array([1, 2 , 4, 5, 6, 3])
print(np.sort(a)[::-1])


[6 5 4 3 2 1]


## 1.3.6 Задание
    Создайте матрицу, выведите ее форму, размер и размерность.

In [5]:
n = np.arange(25).reshape(5, 5)
print("Форма -", np.shape(n))
print("Размер -", np.size(n))
print("Размерность -", np.ndim(n))

Форма - (5, 5)
Размер - 25
Размерность - 2


## 2.3.1 Задание
    Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [6]:
pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/29/d4/1244ab8edf173a10fd601f7e13b9566c1b525c4f365d6bee918e68381889/pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/11/c3/005fcca25ce078d2cc29fd559379817424e94885510568bc1bc53d7d5846/pytz-2024.2-py2.py3-none-any.whl.metadata
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/a6/ab/7e5f53c3b9d14972843a647d8d7a853969a58aecc7559cb3267302c94774/tzdata-2024.2-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 1.3 MB/s eta 0:00:09
    --------------------------------------- 0.2/11.5 MB 2.6 MB/s eta 0:00:05
    --------------------------------------- 0.3/11.5 MB 2.2 MB/s eta 0:00:06
   - -------------------------------------- 0.4/11.5 MB 2.4 MB/s eta 0:00:05



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import pandas as pd
a, b = map(int, input('Введите две координаты').split(" "))
s = pd.Series([a, b], ['a', 'b'])
print(f'расстояние между точками = {abs(s['a'] - s['b'])}')

Введите две координаты 12 67


расстояние между точками = 55


## 2.3.2 Задание
    Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данный можно найти здесь: https://github.com/akmand/datasets)

In [8]:
dataframe = pd.read_csv('adult.csv')
dataframe.head(10)

age         workclass  education_num         marital_status  \
0   39         State-gov             13          Never-married   
1   50  Self-emp-not-inc             13     Married-civ-spouse   
2   38           Private              9               Divorced   
3   53           Private              7     Married-civ-spouse   
4   28           Private             13     Married-civ-spouse   
5   37           Private             14     Married-civ-spouse   
6   49           Private              5  Married-spouse-absent   
7   52  Self-emp-not-inc              9     Married-civ-spouse   
8   31           Private             14          Never-married   
9   42           Private             13     Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   
5    Exec-managerial           Wife  White  Female              40   
6      Other-service  Not-in-family  Other  Female              16   
7    Exec-managerial        Husband  White    Male              45   
8     Prof-specialty  Not-in-family  White  Female              50   
9    Exec-managerial        Husband  White    Male              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K  
5  United-States        0         <=50K  
6          Other        0         <=50K  
7  United-States        0          >50K  
8  United-States    14084          >50K  
9  United-States     5178          >50K

In [9]:
dataframe.tail(10)

age     workclass  education_num      marital_status       occupation  \
45212   48       Private              9  Married-civ-spouse     Adm-clerical   
45213   61       Private              9  Married-civ-spouse            Sales   
45214   31       Private              9  Married-civ-spouse     Craft-repair   
45215   25       Private              9       Never-married    Other-service   
45216   48     Local-gov             14            Divorced    Other-service   
45217   33       Private             13       Never-married   Prof-specialty   
45218   39       Private             13            Divorced   Prof-specialty   
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

        relationship   race  gender  hours_per_week native_country  capital  \
45212        Husband  White    Male              40  United-States        0   
45213        Husband  White    Male              48  United-States        0   
45214        Husband  White    Male              40  United-States        0   
45215      Own-child  White  Female              40  United-States        0   
45216  Not-in-family  White    Male              40  United-States        0   
45217      Own-child  White    Male              40  United-States        0   
45218  Not-in-family  White  Female              36  United-States        0   
45219        Husband  White    Male              50  United-States        0   
45220      Own-child  Other    Male              40  United-States     5455   
45221        Husband  White    Male              60  United-States        0   

      income_status  
45212         <=50K  
45213         <=50K  
45214         <=50K  
45215         <=50K  
45216         <=50K  
45217         <=50K  
45218         <=50K  
45219         <=50K  
45220         <=50K  
45221          >50K

## 2.3.3 Задание
    Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7

In [12]:
dataframe.shape

(45222, 12)

In [13]:
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [14]:
dataframe.loc[8:18]

age         workclass  education_num      marital_status  \
8    31           Private             14       Never-married   
9    42           Private             13  Married-civ-spouse   
10   37           Private             10  Married-civ-spouse   
11   30         State-gov             13  Married-civ-spouse   
12   23           Private             13       Never-married   
13   32           Private             12       Never-married   
14   34           Private              4  Married-civ-spouse   
15   25  Self-emp-not-inc              9       Never-married   
16   32           Private              9       Never-married   
17   38           Private              7  Married-civ-spouse   
18   43  Self-emp-not-inc             14            Divorced   

           occupation   relationship   race  gender  hours_per_week  \
8      Prof-specialty  Not-in-family  White  Female              50   
9     Exec-managerial        Husband  White    Male              40   
10    Exec-managerial        Husband  Other    Male              80   
11     Prof-specialty        Husband  Other    Male              40   
12       Adm-clerical      Own-child  White  Female              30   
13              Sales  Not-in-family  Other    Male              50   
14   Transport-moving        Husband  Other    Male              45   
15    Farming-fishing      Own-child  White    Male              35   
16  Machine-op-inspct      Unmarried  White    Male              40   
17              Sales        Husband  White    Male              50   
18    Exec-managerial      Unmarried  White  Female              45   

   native_country  capital income_status  
8   United-States    14084          >50K  
9   United-States     5178          >50K  
10  United-States        0          >50K  
11          Other        0          >50K  
12  United-States        0         <=50K  
13  United-States        0         <=50K  
14          Other        0         <=50K  
15  United-States        0         <=50K  
16  United-States        0         <=50K  
17  United-States        0         <=50K  
18  United-States        0          >50K

In [15]:
dataframe[dataframe['marital_status'] == 'Never-married'].head(100)

age         workclass  education_num marital_status        occupation  \
0     39         State-gov             13  Never-married      Adm-clerical   
8     31           Private             14  Never-married    Prof-specialty   
12    23           Private             13  Never-married      Adm-clerical   
13    32           Private             12  Never-married             Sales   
15    25  Self-emp-not-inc              9  Never-married   Farming-fishing   
..   ...               ...            ...            ...               ...   
295   29           Private             10  Never-married      Tech-support   
300   29           Private              7  Never-married   Exec-managerial   
305   66           Private              9  Never-married  Transport-moving   
306   41           Private             10  Never-married      Craft-repair   
307   26           Private             13  Never-married      Adm-clerical   

      relationship   race  gender  hours_per_week native_country  capital  \
0    Not-in-family  White    Male              40  United-States     2174   
8    Not-in-family  White  Female              50  United-States    14084   
12       Own-child  White  Female              30  United-States        0   
13   Not-in-family  Other    Male              50  United-States        0   
15       Own-child  White    Male              35  United-States        0   
..             ...    ...     ...             ...            ...      ...   
295  Not-in-family  White  Female              40  United-States        0   
300  Not-in-family  White  Female              40  United-States        0   
305  Not-in-family  White    Male              55  United-States     2050   
306  Not-in-family  Other    Male              45  United-States        0   
307  Not-in-family  White    Male              40  United-States        0   

    income_status  
0           <=50K  
8            >50K  
12          <=50K  
13          <=50K  
15          <=50K  
..            ...  
295         <=50K  
300         <=50K  
305         <=50K  
306         <=50K  
307         <=50K  

[100 rows x 12 columns]

## 3.3.2 Задание
    Загрузить фрейм данных по ссылке:
    https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
    Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования

In [18]:
!pip install scikit-learn

  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/aa/ce/c0b912f2f31aeb1b756a6ba56bcd84dd1f8a148470526a48515a3f4d48cd/scikit_learn-1.5.2-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.6.0 from https://files.pythonhosted.org/packages/aa/7d/43ab67228ef98c6b5dd42ab386eae2d7877036970a0d7e3dd3eb47a0d530/scipy-1.14.1-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.8 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 647.9 kB/s eta 0:00:00
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/91/29/df4b9b42f2be0b623cbd5e2140cafcaa2bef0759a00b7b70104dcfe2fb51/joblib-1.4.2-py3-none-any.whl.metadata
  Obtaining dependency information for threadpoolctl>=3.1.0 fr


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [30]:
from sklearn import preprocessing
iris = pd.read_csv('iris.csv')

x_array = np.array(iris['sepal_length_cm'])
normalized_xarr = preprocessing.MinMaxScaler([x_array])
print(normalized_xarr)
y_array = np.array(iris['sepal_width_cm'])
normalized_yarr = preprocessing.StandardScaler().fit_transform([y_array])
normalized_yarr


MinMaxScaler(feature_range=[array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])])


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])